### ISSUE TITLE
Bug Error 'JsonFormat' is not a class or namespace

### ISSUE THREAD

**Issue by stuqqq** [eteran/qjson4#10]
From file QJsondocument.cpp 206 Line
``` bool compact = (format == JsonFormat::Compact); ```
Fixed ```  bool compact = (Format == QJsonDocument::Compact);  ```

**Comment by barracuda156** [comment]
Yes, I get the same error building on macOS:
```
QJsonDocument.cpp: In member function ‘QString QJsonDocument::toJson(const QJsonValue&, QJsonDocument::JsonFormat, int) const’:
QJsonDocument.cpp:206: error: ‘JsonFormat’ is not a class or namespace
make: *** [.release/obj/QJsonDocument.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by barracuda156** [comment]
@eteran Could this be fixed, please?

**Comment by eteran** [comment]
@barracuda156 sure, I actually hadn't noticed this issue, I'll get a fix in ASAP.

**Comment by eteran** [comment]
Done

**Comment by barracuda156** [comment]
> Done

Thank you!
