### ISSUE TITLE
encode and decode Int issus

### ISSUE THREAD

**Issue by enefry** [eteran/qjson4#3]
QVariantMap map;
    map.insert ("int",INT_MAX);
    map.insert ("double",3.1415926);
    map.insert ("name","hell");
    QJsonDocument doc = QJsonDocument::fromVariant (map);
    qDebug()<< doc.toJson ();
the result will be 
    "{"double": 3.14159,"int": 2.14748e+09,"name": "hell"}"

**Comment by eteran** [comment]
Thanks for the report, I'll take a look. Do you know if the real Qt JSON API has a similar issue or not? I ask because the issue stems from using a double to store all numeric data, which unfortunately can't handle the full range of integer values. I wonder if Qt made similar chocies.

**Comment by enefry** [comment]
I had run this code in qt5.4 and get right result 

but I found  5.4.1_vs2013\5.4\Src\qtbase\src\corelib\json\qjsonvalue.cpp

QJsonValue QJsonValue::fromVariant(const QVariant &variant)
{
    switch (variant.userType()) {
    case QVariant::Bool:
        return QJsonValue(variant.toBool());
    case QVariant::Int:
    case QMetaType::Float:
    case QVariant::Double:
    case QVariant::LongLong:
    case QVariant::ULongLong:
    case QVariant::UInt:
        return QJsonValue(variant.toDouble());
    case QVariant::String:
        return QJsonValue(variant.toString());
    case QVariant::StringList:
        return QJsonValue(QJsonArray::fromStringList(variant.toStringList()));
    case QVariant::List:
        return QJsonValue(QJsonArray::fromVariantList(variant.toList()));
    case QVariant::Map:
        return QJsonValue(QJsonObject::fromVariantMap(variant.toMap()));
    default:
        break;
    }
    QString string = variant.toString();
    if (string.isEmpty())
        return QJsonValue();
    return QJsonValue(string);
}

**Comment by enefry** [comment]
But Qt5 use 0X7FFFFFFFFFFFFFFFLL will be "int64": 9.2233720368547758e+18,

**Comment by enefry** [comment]
issus at  format double to string 
modify :
QString QJsonDocument::toJson(const QJsonValue &v, JsonFormat format) const {
...
to:
	case QJsonValue::Double:
    {
        double d = v.toDouble ();
        if (qIsFinite(d)) // +2 to format to ensure the expected precision
                   ss <<  QByteArray::number(d, 'g', 15 + 2); // ::digits10 is 15
               else
                   ss <<  "null"; // +INF || -INF || NaN (see RFC4627#section2.4)
        break;
    }

will same behavior with qt5
