### ISSUE TITLE
Tagged version releases

### ISSUE THREAD

**Issue by archey** [eteran/qjson4#4]
Would it be possible to tag a release on this, I am trying to pull in the new version to ArchStrike of edb-debugger which requires this library.

**Comment by archey** [comment]
Scratch that, we will just use the actual released source of edb-debugger due to the submodule issue.

**Comment by eteran** [comment]
Yea, was gonna say that the sub-modules are bound to specific commits, but sure, in general we can make some tags at major change points in the future :-)
